// Generated by CoffeeScript 1.6.3
(function() {
  var penn, plan1;

  penn = {
    name: "University of Pennsylvania",
    email_domain: ".upenn.edu",
    cover_image: "/public/img/penn_cover.jpg",
    plans: []
  };

  plan1 = {
    title: "College House, Hill Square",
    image_thumbnail: "/public/img/college_house_thumb.jpg",
    supporters: [],
    proposals: [],
    elements: [
      {
        type: "text",
        _class: "subheader",
        content: "Planning Strategy"
      }, {
        type: "text",
        _class: "",
        content: "The New College House will establish a gateway to campus, as it is located at a key pedestrian approach from the northeastern corner of the University. It will be the first building one encounters coming from the 30th Street Amtrak and Regional Rail Station, and will front onto Woodland Walk, one of the three main pedestrian paths identified in the Campus Development Plan. A new public open space or commons will enliven the center of this important residential quadrangle."
      }, {
        type: "text",
        _class: "subheader",
        content: "Program"
      }, {
        type: "text",
        _class: "",
        content: "A new 300-400 bed College House, including residential advisors, faculty, and house master suites. The ground floor will feature public amenities such as dining and social spaces."
      }, {
        type: "text",
        _class: "subheader",
        content: "Total Project Cost"
      }, {
        type: "text",
        _class: "",
        content: "TBD (estimated at $100,000,000)"
      }, {
        type: "text",
        _class: "subheader",
        content: "Area"
      }, {
        type: "text",
        _class: "",
        content: "TBD (estimated 200,000 GSF)"
      }, {
        type: "image",
        _class: "",
        content: "/public/img/college_house_large_1.jpg"
      }, {
        type: "image",
        _class: "",
        content: "/public/img/college_house_large_2.jpg"
      }, {
        type: "model",
        _class: "",
        content: "731b50acda004fc78f130bdc24028804"
      }, {
        type: "location",
        _class: "",
        content: [39.953067, -75.190902]
      }
    ]
  };

}).call(this);
