// Generated by CoffeeScript 1.6.3
var collection, db, log, mongo;

mongo = require('mongoskin', log = console.log);

db = mongo.db('localhost:27017/testdb', {
  w: 0
});

collection = db.collection('production');

module.exports = collection;
