// Generated by CoffeeScript 1.6.3
(function() {
  var formData, fs, i, request, uploadImage, uploadModel;

  request = require('request');

  formData = require('form-data');

  fs = require('fs');

  i = 0;

  uploadModel = function(title, modelFile, callback) {
    console.log("Title = " + title + ", modelFile = " + modelFile);
    i++;
    return callback(null, 'SketchFabId_' + i);
  };

  uploadImage = function(imageFile, callback) {
    console.log("imageFile = " + imageFile);
    i++;
    return callback(null, 'imageFile_' + i);
  };

  module.exports = {
    uploadImage: uploadImage,
    uploadModel: uploadModel
  };

}).call(this);
