// Generated by CoffeeScript 1.6.3
(function() {
  var models;

  models = require('./models');

  models.School.create({
    name: 'name',
    email_domain: 'domain',
    plans: []
  }, function(_id) {
    models.School.addPlan(_id, {
      title: 'title',
      image_thumbnail: 'thumb',
      supporters: [],
      proposals: [],
      elements: []
    }, function(plan_id) {
      models.Plan.addProposal(plan_id, {
        this_is: 'a proposal'
      }, function(prop_id) {
        return console.log("proposal ID is " + prop_id);
      });
      return models.Plan.addSupporter(plan_id, {
        name: "Sammy Supporter",
        email: "sam@supportmemaybe.net"
      });
    });
    return models.School.update(_id, {
      name: 'Penn',
      email_domain: 'upenn.edu'
    });
  });

}).call(this);
