// Generated by CoffeeScript 1.6.3
(function() {
  var formData, fs, request, uploadImage, uploadModel;

  request = require('request');

  formData = require('form-data');

  fs = require('fs');

  uploadModel = function(title, modelFile, callback) {
    return fs.readFile(modelFile.path(function(err, data) {
      var form;
      form = new formData();
      form.append('title', title);
      form.append('fileModel', data);
      form.append('token', process.env.SKETCHFAB_API_KEY);
      form.append('private', 1);
      return form.getLength(function(err, length) {
        var r;
        if (err) {
          callback(err);
        }
        r = request.post('https://api.sketchfab.com/v1/models', {
          headers: {
            'content-length': length
          }
        }, function(err, response, body) {
          var e, fileName, newPath;
          fileName = body.result.id(+'.dae');
          newPath = __dirname + '/public/models/' + filename;
          fs.writeFile(newPath, data, function(err) {
            return callback(err);
          });
          if (err) {
            callback(err);
          }
          try {
            body = JSON.parse(body);
          } catch (_error) {
            e = _error;
            callback(e);
          }
          if (body.success !== true) {
            callback(new Error(body.error));
          }
          return callback(null, body.result.id);
        });
        return r._form = form;
      });
    }));
  };

  uploadImage = function(imageFile, callback) {
    return fs.readFile(imageFile.path(function(err, data) {
      var fileName, newPath;
      fileName = imageFile.path.split('/')[2] + '.' + imageFile.name.split('.')[1];
      newPath = __dirname + '/public/img/' + fileName;
      return fs.writeFile(newPath, data, function(err) {
        return callback(err, fileName);
      });
    }));
  };

}).call(this);
